version: '3'
services:
  chachacha_validator1:
    container_name: chachacha_validator1
    ports:
      - "18833:9933"
      - "18844:9944"
      - "10334:30333"
    image: centrifugeio/rococo:chachacha-v1
    volumes:
      - "chachacha-validator1:/data"
    command:
      polkadot
      --validator
      --chain rococo-chachacha
      --name polkafoundry_chachacha1
      --rpc-cors=all
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.1
  ################################################################
  chachacha_validator2:
    container_name: chachacha_validator2
    ports:
      - "17843:9933"
      - "17844:9944"
      - "10335:30333"
    image: centrifugeio/rococo:chachacha-v1
    volumes:
      - "chachacha-validator2:/data"
    command:
      polkadot
      --validator
      --chain rococo-chachacha
      --name polkafoundry_chachacha2
      --rpc-cors=all
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.2
  ################################################################
  chachacha_collator:
    container_name: pkf_chachacha_collator
    ports:
      - "16644:9944"
      - "16633:9933"
      - "10336:30333"
    image: halongbay
    volumes:
      - "pkf-chachacha-collator:/data"
      - ../specs/chachacha:/specs/chachacha
    command:
      --parachain-id=14
      --collator
      --unsafe-rpc-external
      --rpc-cors=all
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --discover-local
      --
      --execution=wasm
      --chain /specs/chachacha/rococo-chachacha.json
      --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.3

volumes:
  chachacha-validator1:
  chachacha-validator2:
  pkf-chachacha-collator:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/16
