version: '3'
services:
  chachacha_validator1:
    container_name: chachacha_validator1
    ports:
      - "18883:9933"
      - "18884:9944"
      - "10384:30333"
    image: centrifugeio/rococo:chachacha-v1
    volumes:
      - "pkf-chachacha-validator1:/data"
    command:
      polkadot
      --validator
      --chain rococo-chachacha
      --name pkf_chachacha1
      --rpc-cors=all
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.1
  ################################################################
  chachacha_validator2:
    container_name: chachacha_validator2
    ports:
      - "17883:9933"
      - "17884:9944"
      - "10385:30333"
    image: centrifugeio/rococo:chachacha-v1
    volumes:
      - "pkf-chachacha-validator2:/data"
    command:
      polkadot
      --validator
      --chain rococo-chachacha
      --name pkf_chachacha2
      --rpc-cors=all
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.2
  ################################################################
  chachacha_collator:
    container_name: pkf_chachacha_collator
    ports:
      - "16684:9944"
      - "16683:9933"
      - "10386:30333"
    image: public.ecr.aws/o0b6j5s9/polkafoundry:rococo
    volumes:
      - "pkf-chachacha-collator:/data"
      - ../specs/chachacha:/specs/chachacha
    command:
      --parachain-id=14
      --collator
      --unsafe-rpc-external
      --rpc-cors=all
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --discover-local
      --chain /specs/chachacha/halongbaySpec.json
      --
      --execution=wasm
      --chain /specs/chachacha/rococo-chachacha.json
      --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.3

volumes:
  pkf-chachacha-validator1:
  pkf-chachacha-validator2:
  pkf-chachacha-collator:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/16
