version: '3'
services:
  node_alice:
    container_name: rococo_alice
    ports:
      - "9933:9933"
      - "9944:9944"
    image: parity/rococo:rococo-v1-0.8.29-3d03552a-0189c7ce
    volumes:
      - "polkadot-data-alice:/data"
      - ../specs/halongbay-v1:/specs/halongbay-v1
    command:  --alice 
              --chain /specs/halongbay-v1/rococo-local.json
              --name node_alice
              --rpc-cors=all
              --unsafe-rpc-external 
              --unsafe-ws-external 
              --rpc-methods=Unsafe 
              --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.1
################################################################
  node_bob:
    container_name: rococo_bob
    ports:
      - "30330:30333"
      - "8844:9944"
      - "8833:9933"
    image: parity/rococo:rococo-v1-0.8.29-3d03552a-0189c7ce
    volumes:
      - "polkadot-data-bob:/data"
      - ../specs/halongbay-v1:/specs/halongbay-v1
    links:
      - "node_alice:alice"
    command:  --bob 
              --chain /specs/halongbay-v1/rococo-local.json
              --rpc-cors=all
              --unsafe-rpc-external 
              --unsafe-ws-external
              --rpc-methods=Unsafe
              --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.2
################################################################
  node_validator:
    container_name: rococo_validator
    ports:
      - "7744:9944"
      - "7733:9933"
      - "30331:30333"
    image: parity/rococo:rococo-v1-0.8.29-3d03552a-0189c7ce
    volumes:
      - "polkadot-data-validator:/data"
      - ../specs/halongbay-v1:/specs/halongbay-v1
    links:
      - "node_alice:alice"
      - "node_bob:bob"
    command: --validator 
              --chain /specs/halongbay-v1/rococo-local.json
              --unsafe-rpc-external
              --rpc-cors all
              --unsafe-ws-external
              --rpc-methods=Unsafe
              --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.3
###############################################################
  node_halongbay_v1_collator:
    container_name: halongbay-v1_collator
    ports:
      - "5544:9944"
      - "5533:9933"
      - "20336:30333"
    image: public.ecr.aws/o0b6j5s9/polkafoundry:halongbay-v1
    volumes:
      - "halongbay-collator-data:/data"
      - ../specs/halongbay-v1:/specs/halongbay-v1
    # links:
    #   - "node_alice:alice"
    command: --collator 
            --parachain-id 14
            --discover-local
            --
            --execution wasm
            --chain /specs/halongbay-v1/rococo-local.json
            --port 30335
            --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.4
###############################################################
  node_halongbay_v1_full_node:
    container_name: halongbay-v1_FullNode
    ports:
      - "4444:9944"
      - "4433:9933"
      - "20337:30333"
    image: public.ecr.aws/o0b6j5s9/polkafoundry:halongbay-v1
    volumes:
      - "halongbay-fullnode-data:/data"
      - ../specs/halongbay-v1:/specs/halongbay-v1
    # links:
    #   - "node_alice:alice"
    command: --parachain-id 14
            --discover-local
            --
            --execution wasm
            --chain /specs/halongbay-v1/rococo-local.json
            --port 30335
            --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.5

volumes:
  polkadot-data-alice:
  polkadot-data-bob:
  polkadot-data-validator:
  halongbay-collator-data:
  halongbay-fullnode-data:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/16
