version: '3'
services:
  node_alice:
    container_name: kusama_alice
    ports:
      - "9944:9944"
      - "30444:30333"
    image: icetealabs/test:polkadot-v0.9.4
    volumes:
      - "polkadot-data-alice:/data"
      -  ../node/res:/spec
    command:
      polkadot
      --alice
      --base-path /tmp/alice
      --chain /spec/rococo-local.json
      --rpc-cors=all
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-methods=Unsafe
    networks:
      testing_net:
        ipv4_address: 172.99.1.1
  ################################################################
  node_bob:
    container_name: kusama_bob
    ports:
      - "9955:9944"
      - "30555:30333"
    image: icetealabs/test:polkadot-v0.9.4
    volumes:
      - "polkadot-data-bob:/data"
      - ../node/res:/spec
    links:
      - "node_alice:alice"
    command:
      polkadot
      --bob
      --base-path /tmp/bob
      --chain /spec/rococo-local.json
      --rpc-cors=all
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-methods=Unsafe
    networks:
      testing_net:
        ipv4_address: 172.99.1.2
  ################################################################
  node_charlie:
    container_name: kusama_charlie
    ports:
      - "9966:9944"
      - "30666:30333"
    image: icetealabs/test:polkadot-v0.9.4
    volumes:
      - "polkadot-data-charlie:/data"
      - ../node/res:/spec
    links:
      - "node_alice:alice"
    command:
      polkadot
      --charlie
      --base-path /tmp/charlie
      --chain /spec/rococo-local.json
      --rpc-cors=all
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-methods=Unsafe
    networks:
      testing_net:
        ipv4_address: 172.99.1.3
  ################################################################
  node_dave:
    container_name: kusama_dave
    ports:
      - "9977:9944"
      - "30777:30333"
    image: icetealabs/test:polkadot-v0.9.4
    volumes:
      - "polkadot-data-dave:/data"
      - ../node/res:/spec
    links:
      - "node_alice:alice"
    command:
      polkadot
      --dave
      --base-path /tmp/dave
      --chain /spec/rococo-local.json
      --rpc-cors=all
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-methods=Unsafe
    networks:
      testing_net:
        ipv4_address: 172.99.1.4
  ################################################################
  node_polkasmith_collator:
    container_name: polkasmith_collator1
    ports:
      - "9988:9944"
      - "9987:9933"
      - "31200:30333"
    image: icetealabs/polkasmith:1.0.0
    volumes:
      - "polkasmith-collator-data1:/data"
      - ../node/res:/spec
    # links:
    #   - "node_alice:alice"
    command: --collator
      --unsafe-rpc-external
      --rpc-cors all
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --parachain-id=2009
      --force-chain=polkasmith
      --chain /spec/polkasmith.json
      --
      --chain /spec/rococo-local.json
      --execution wasm
    networks:
      testing_net:
        ipv4_address: 172.99.1.5
  ################################################################
  node_polkasmith_collator2:
    container_name: polkasmith_collator2
    ports:
      - "9989:9944"
      - "9986:9933"
      - "31201:30333"
    image: icetealabs/polkasmith:1.0.0
    volumes:
      - "polkasmith-collator-data2:/data"
      - ../node/res:/spec
    # links:
    #   - "node_alice:alice"
    command: --collator
      --unsafe-rpc-external
      --rpc-cors all
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --parachain-id=2009
      --force-chain=polkasmith
      --chain /spec/polkasmith.json
      --
      --chain /spec/rococo-local.json
      --execution wasm
    networks:
      testing_net:
        ipv4_address: 172.99.1.6

volumes:
  polkadot-data-alice:
  polkadot-data-bob:
  polkadot-data-charlie:
  polkadot-data-dave:

  polkasmith-collator-data1:
  polkasmith-collator-data2:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/16
