version: '3'
services:
  node_alice:
    container_name: rococo_alice
    ports:
      - "9933:9933"
      - "9944:9944"
    image: tungicetea/rococo:latest
    volumes:
      - "polkadot-data-alice:/data"
      - ../node/res:/res
    command:  --alice
      --chain /res/rococo-local.json
      --name node_alice
      --rpc-cors=all
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.1
  ################################################################
  node_bob:
    container_name: rococo_bob
    ports:
      - "30330:30333"
      - "8844:9944"
      - "8833:9933"
    image: tungicetea/rococo:latest
    volumes:
      - "polkadot-data-bob:/data"
      - ../node/res:/res
    links:
      - "node_alice:alice"
    command:  --bob
      --chain /res/rococo-local.json
      --rpc-cors=all
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.2
  ################################################################
  node_halongbay_v1_collator:
    container_name: halongbay-v1_collator
    ports:
      - "5544:9944"
      - "5533:9933"
      - "20336:30333"
    image: halongbay
    volumes:
      - "halongbay-collator-data:/data"
      - ../node/res:/res
    # links:
    #   - "node_alice:alice"
    command: --collator
      --unsafe-rpc-external
      --rpc-cors all
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --parachain-id 1111
      --author-id=0xea8e9d3cfedc8afec25785703681d424e6aba10b728927b89d87a3776b47ee32
      --discover-local
      --chain /res/halongbay.json
      --
      --execution wasm
      --chain /res/rococo-local.json
      --port 30335
      --discover-local
    networks:
      testing_net:
        ipv4_address: 172.99.1.4

volumes:
  polkadot-data-alice:
  polkadot-data-bob:
  halongbay-collator-data:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/16
