
[package]
authors = ['Polkafoundry']
build = 'build.rs'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2018'
homepage = 'https://polkafoundry.com'
license = 'Unlicense'
name = 'polkafoundry'
repository = 'https://github.com/polkafoundry/newpolka/'
version = '0.0.1'

[[bin]]
name = 'polkafoundry'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }

[dependencies]
jsonrpc-core = '15.1.0'
jsonrpc-pubsub = '15.1.0'
structopt = '0.3.8'
futures = { version = '0.3.4' }
log = '0.4.8'
codec = { package = 'parity-scale-codec', version = '2.0.0' }
serde = { features = ['derive'], version = '1.0.119' }
hex-literal = '0.3.1'
hex = '0.4.3'
async-trait = { version = "0.1.48" }

# local dependencies
author-inherent = { path = '../pallets/author-inherent' }

polkafoundry-runtime = { path = '../runtime/polkafoundry', version = '0.0.1', optional = true }
polkasmith-runtime = { path = '../runtime/polkasmith', version = '0.0.1', optional = true }
halongbay-runtime = { path = '../runtime/halongbay', version = '0.0.1', optional = true }

# Substrate dependencies
frame-benchmarking = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
frame-benchmarking-cli = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }

pallet-transaction-payment-rpc = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
pallet-aura = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }

sc-basic-authorship = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-cli = { git = 'https://github.com/paritytech/substrate.git', branch = 'master', features = ['wasmtime'] }
sc-client-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-consensus = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-executor = { git = 'https://github.com/paritytech/substrate.git', branch = 'master', features = ['wasmtime'] }
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-keystore = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-rpc = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-rpc-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-service = { git = 'https://github.com/paritytech/substrate.git', branch = 'master', features = ['wasmtime'] }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-telemetry = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-network = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-consensus-manual-seal = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sc-tracing = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }

sp-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-block-builder = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-blockchain = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-consensus = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-core = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-inherents = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-timestamp = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-trie = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-offchain = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-session = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-storage = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
sp-keystore = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
substrate-prometheus-endpoint = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }

substrate-frame-rpc-system = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }

fc-consensus = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'polkasmith-v0.0.1' }
fp-consensus = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'polkasmith-v0.0.1' }
fp-rpc = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'polkasmith-v0.0.1' }
fc-rpc = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'polkasmith-v0.0.1' }
fc-rpc-core = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'polkasmith-v0.0.1' }
frame-system-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }
pallet-transaction-payment-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'master' }

cumulus-client-consensus-relay-chain = { git = 'https://github.com/paritytech/cumulus.git', branch = 'master' }
cumulus-client-service = { git = 'https://github.com/paritytech/cumulus.git', branch = 'master' }
cumulus-client-network = { git = 'https://github.com/paritytech/cumulus.git', branch = 'master' }
cumulus-primitives-core = { git = 'https://github.com/paritytech/cumulus.git', branch = 'master' }
cumulus-primitives-parachain-inherent = { git = 'https://github.com/paritytech/cumulus.git', branch = 'master' }
cumulus-test-relay-sproof-builder = { git = 'https://github.com/paritytech/cumulus.git', branch = 'master' }
cumulus-client-consensus-aura = { git = 'https://github.com/paritytech/cumulus.git', branch = 'master' }
cumulus-client-consensus-common = { git = 'https://github.com/paritytech/cumulus.git', branch = 'master' }
cumulus-pallet-aura-ext = { git = 'https://github.com/paritytech/cumulus.git', branch = 'master' }
clap = { version = '2.33' }

polkadot-primitives = { git = 'https://github.com/paritytech/polkadot', branch = 'master' }
polkadot-service = { git = 'https://github.com/paritytech/polkadot', branch = 'master' }
polkadot-cli = { git = 'https://github.com/paritytech/polkadot', branch = 'master' }
polkadot-parachain = { git = 'https://github.com/paritytech/polkadot', branch = 'master' }

pallet-evm = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'polkasmith-v0.0.1' }
runtime-primitives = { path = '../primitives' }

[features]
default = [
    'halongbay'
]
polkafoundry = [
    'polkafoundry-runtime'
]
polkasmith = [
    'polkasmith-runtime'
]
halongbay = [
    'halongbay-runtime'
]

runtime-benchmarks = [
    'polkafoundry-runtime/runtime-benchmarks',
    'polkasmith-runtime/runtime-benchmarks',
    'halongbay-runtime/runtime-benchmarks',
]

