
[package]
authors = ['Polkafoundry']
build = 'build.rs'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2018'
homepage = 'https://polkafoundry.com'
license = 'Unlicense'
name = 'polkafoundry'
repository = 'https://github.com/polkafoundry/newpolka/'
version = '0.0.1'

[[bin]]
name = 'polkafoundry'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }

[dependencies]
jsonrpc-core = '15.1.0'
jsonrpc-pubsub = '15.1.0'
structopt = '0.3.8'
futures = { version = '0.3.4' }
log = '0.4.8'
codec = { package = 'parity-scale-codec', version = '2.0.0' }
serde = { features = ['derive'], version = '1.0.119' }
hex-literal = '0.3.1'
hex = '0.4.3'

# local dependencies
polkafoundry-runtime = { path = '../runtime', version = '0.0.1' }

# Substrate dependencies
frame-benchmarking = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
frame-benchmarking-cli = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }

pallet-transaction-payment-rpc = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }

sc-basic-authorship = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-cli = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1', features = ['wasmtime'] }
sc-client-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-consensus = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-executor = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1', features = ['wasmtime'] }
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-keystore = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-rpc = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-rpc-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-service = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1', features = ['wasmtime'] }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-telemetry = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-network = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-consensus-manual-seal = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sc-tracing = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }

sp-api = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-block-builder = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-blockchain = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-consensus = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-core = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-inherents = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-timestamp = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }
sp-trie = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }

substrate-frame-rpc-system = { git = 'https://github.com/paritytech/substrate.git', branch = 'rococo-v1' }

fc-consensus = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'halongbay' }
fp-consensus = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'halongbay' }
fp-rpc = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'halongbay' }
fc-rpc = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'halongbay' }
fc-rpc-core = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'halongbay' }

cumulus-client-consensus-relay-chain = { git = 'https://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }
cumulus-client-service = { git = 'https://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }
cumulus-client-network = { git = 'https://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }
cumulus-primitives-core = { git = 'https://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }
cumulus-primitives-parachain-inherent = { git = 'https://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }
cumulus-test-relay-sproof-builder = { git = 'https://github.com/paritytech/cumulus.git', branch = 'rococo-v1' }

polkadot-primitives = { git = 'https://github.com/paritytech/polkadot', branch = 'rococo-v1' }
polkadot-service = { git = 'https://github.com/paritytech/polkadot', branch = 'rococo-v1' }
polkadot-cli = { git = 'https://github.com/paritytech/polkadot', branch = 'rococo-v1' }
polkadot-test-service = { git = 'https://github.com/paritytech/polkadot', branch = 'rococo-v1' }
polkadot-parachain = { git = 'https://github.com/paritytech/polkadot', branch = 'rococo-v1' }

pallet-evm = { git = 'https://github.com/polkafoundry/frontier.git', branch = 'halongbay' }

[features]
default = []
runtime-benchmarks = ['polkafoundry-runtime/runtime-benchmarks']
